### ISSUE TITLE
AHK v2 support

### ISSUE THREAD

**Issue by compulim** [laurence-myers/midi-to-macro#7]
Will be great if there is a cleaner version with AHK v2 support.

Maybe start with turning some `gosub` into functions.

I have some code for running `winmm.dll` in AHK v2, you can refer it here, https://github.com/compulim/autohotkey-boss-fs-1-wl. However, I didn't port the GUI there.

**Comment by laurence-myers** [comment]
Thanks for the prompt! I've rewritten the script from the ground up, and it now requires AHK v2. It'd be lovely if you have time to review the changes and provide any feedback. 

Fixed in #8
